name = "sypsee/growapond"
version = "0.1.0"
authors = ["sypse"]
license = "MIT"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
lune = "^0.8.9"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }

[dependencies]
jecs_nightly = { name = "marked/jecs_nightly", version = "^0.6.0-rc.1-nightly.20250509T001119Z" }
